# Generated by Django 3.1.7 on 2021-03-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyMobile',
            fields=[
                ('token', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=13, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
